Use LogbookDB;

CREATE TABLE People (PK_PeopleID INT PRIMARY KEY, PeopleNric VARCHAR(20) NOT NULL, PeopleName VARCHAR(300) NOT NULL);

CREATE TABLE SignIn (PK_SignInID INT PRIMARY KEY, SignInDate VARCHAR(10) NOT NULL, SignInTime VARCHAR(8) NOT NULL);

CREATE TABLE SignOut (PK_SignOutID INT PRIMARY KEY, SignOutDate VARCHAR(10) NOT NULL, SignOutTime VARCHAR(8) NOT NULL);

CREATE TABLE Records (PK_RecordID INT PRIMARY KEY, 
					  FK_PeopleID INT FOREIGN KEY REFERENCES People(PK_PeopleID) NOT NULL, 
					  FK_SignInID INT FOREIGN KEY REFERENCES SignIn(PK_SignInID) NOT NULL, 
					  FK_SignOutID INT FOREIGN KEY REFERENCES SignOut(PK_SignOutID) NOT NULL, 
					  Reason VARCHAR(300) NOT NULL);

